EFCore.NamingConventions/NamingConventions/Internal/SnakeCaseNameRewriter.cs
Reflecting changes from npgsql/npgsql#2697.
=> Decreased memory usage in name rewriter

EFCore.NamingConventions.Test/LowerCaseNamingTest.cs, EFCore.NamingConventions.Test/RewriterTestBase.cs, EFCore.NamingConventions.Test/SnakeCaseNamingTest.cs, EFCore.NamingConventions.Test/UpperCaseNamingTest.cs, EFCore.NamingConventions/NamingConventions/Internal/NameRewriterBase.cs, EFCore.NamingConventions/NamingConventions/Internal/NamingConventionSetPlugin.cs
Closes #3
@YohDeadfall test Foreign_key_name_is_rewritten is failing, may be an issue with the snake case logic, can you take a look?
=> Rewrite constraint and index names

README.md
Updated link to the latest version.
=> Docs: Fixed NuGet Link

EFCore.NamingConventions.Test/UpperSnakeCaseNamingTests.cs, EFCore.NamingConventions/NamingConventions/Internal/NamingConvention.cs, EFCore.NamingConventions/NamingConventions/Internal/NamingConventionSetPlugin.cs, EFCore.NamingConventions/NamingConventions/Internal/NamingConventionsOptionsExtension.cs, EFCore.NamingConventions/NamingConventions/Internal/UpperSnakeCaseNameRewriter.cs, EFCore.NamingConventions/NamingConventionsExtensions.cs
=> Upper snake case naming convention

.github/workflows/build.yml, Directory.Build.props, Directory.Build.targets, EFCore.NamingConventions.Test/EFCore.NamingConventions.Test.csproj, EFCore.NamingConventions.Test/NameRewritingConventionTest.cs, EFCore.NamingConventions.Test/TestUtilities/InMemoryTestHelpers.cs, EFCore.NamingConventions/EFCore.NamingConventions.csproj, EFCore.NamingConventions/Internal/NameRewritingConvention.cs, EFCore.NamingConventions/Internal/NamingConventionSetPlugin.cs, EFCore.NamingConventions/Internal/NamingConventionsOptionsExtension.cs, EFCore.NamingConventions/NamingConventionsExtensions.cs, global.json
* Use EF Core 5.0
* Fixes around TPH, owned entity management
* Redid tests
Fixes #45
Closes #46
Fixes #41
@AndriySvyryd if you feel like it, you can take a look at this. I know there are various edge cases which aren't taken care of (conventions are complicated), but hopefully this covers most mainstream scenarios, including new stuff in 5.0.
=> Big overhaul for 5.0

Directory.Build.targets, EFCore.NamingConventions.Test/EFCore.NamingConventions.Test.csproj, EFCore.NamingConventions.Test/EndToEndTest.cs, EFCore.NamingConventions.Test/NameRewritingConventionTest.cs, EFCore.NamingConventions/Internal/NameRewritingConvention.cs, EFCore.NamingConventions/Internal/NamingConventionSetPlugin.cs
=> Proper support for table splitting

EFCore.NamingConventions.Test/NameRewritingConventionTest.cs, EFCore.NamingConventions/Internal/NameRewritingConvention.cs
=> Avoiding rewriting PK name for owned entity in a TPT hierarchy

EFCore.NamingConventions.Test/NameRewritingConventionTest.cs, EFCore.NamingConventions/Internal/NameRewritingConvention.cs
=> Fix issues around setting the owner's table name explicitly

EFCore.NamingConventions.Test/NameRewritingConventionTest.cs, EFCore.NamingConventions/Internal/NameRewritingConvention.cs
=> Don't create table for View/SqlQuery/Function-mapped entity types

Directory.Packages.props, EFCore.NamingConventions.Test/NameRewritingConventionTest.cs, EFCore.NamingConventions/Check.cs, EFCore.NamingConventions/EFCore.NamingConventions.csproj, EFCore.NamingConventions/Internal/NameRewritingConvention.cs, EFCore.NamingConventions/Internal/NamingConventionSetPlugin.cs, EFCore.NamingConventions/Internal/NamingConventionsOptionsExtension.cs, EFCore.NamingConventions/Internal/SnakeCaseNameRewriter.cs, EFCore.NamingConventions/NamingConventionsExtensions.cs
And annotate the plugin for nullability.
=> Check name for null before attempting to rewrite

Directory.Build.props, EFCore.NamingConventions.Test/EFCore.NamingConventions.Test.csproj, EFCore.NamingConventions.Test/NameRewritingConventionTest.cs, EFCore.NamingConventions/EFCore.NamingConventions.csproj, EFCore.NamingConventions/Internal/NameRewritingConvention.cs
Also turn on nullability for the tests
Closes #181
Closes #177
=> TPC support

EFCore.NamingConventions/Internal/NameRewritingConvention.cs
=> Fix JSON collection navigations

EFCore.NamingConventions.Test/NameRewritingConventionTest.cs, EFCore.NamingConventions/Internal/NameRewritingConvention.cs
=> Fix owned JSON support and improve owned in general

EFCore.NamingConventions.Test/NameRewritingConventionTest.cs, EFCore.NamingConventions.sln.DotSettings, EFCore.NamingConventions/Internal/NameRewritingConvention.cs
=> Fix setting of table names in hierarchies

EFCore.NamingConventions.Test/IntegrationTest.cs, EFCore.NamingConventions.Test/NamingConventionSetPluginTest.cs, EFCore.NamingConventions.Test/NamingConventionsOptionsExtensionTest.cs, EFCore.NamingConventions/Internal/NamingConventionSetPlugin.cs, EFCore.NamingConventions/Internal/NamingConventionsOptionsExtension.cs
Replaces #120, thanks to @Azmond.
Fixes #119
=> Fix case where no naming convention is configured

EFCore.NamingConventions.Test/NameRewritingConventionTest.cs, EFCore.NamingConventions/Internal/NameRewritingConvention.cs, EFCore.NamingConventions/Internal/NamingConventionSetPlugin.cs
Replaces #215 and #149 - thanks @matheus-inacio and @asenkyr.
Fixes #148
Fixes #198
=> Added 'FK property changed' convention and test.

EFCore.NamingConventions.Test/IntegrationTest.cs, EFCore.NamingConventions.Test/NameRewritingConventionTest.cs, EFCore.NamingConventions/Internal/NameRewritingConvention.cs
=> Fix table naming to be inferred from DbSet property again

EFCore.NamingConventions.Test/IntegrationTest.cs, EFCore.NamingConventions/Internal/NameRewritingConvention.cs
=> Fix DbSet naming for hierarchies

EFCore.NamingConventions.Test/NameRewritingConventionTest.cs, EFCore.NamingConventions/Internal/NameRewritingConvention.cs
=> Fix foreign key property change when foreign key is no longer in the model

EFCore.NamingConventions.Test/IntegrationTest.cs, EFCore.NamingConventions/Internal/NameRewritingConvention.cs
=> Fix index/fk hierarchy rewriting logic

EFCore.NamingConventions.Test/IntegrationTest.cs, EFCore.NamingConventions.Test/NameRewritingConventionTest.cs, EFCore.NamingConventions.Test/NamingConventionSetPluginTest.cs, EFCore.NamingConventions/Internal/NameRewritingConvention.cs, EFCore.NamingConventions/Internal/NamingConventionSetPlugin.cs
=> Yet more fixes to table naming in hierarchies and DbSet naming

EFCore.NamingConventions.Test/NameRewritingConventionTest.cs, EFCore.NamingConventions/Internal/NameRewritingConvention.cs
=> Correct nested owned JSON processing
